name: Build STAGING Kernel

on: 
  push:
    branches:
      - fuse

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get build date
      id: get_date
      run: |
        echo ::set-output name=date::$(date '+%Y%m%d-%H')

    - name: Run kernel build script
      run: |
        export TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
        export ZIPNAME=FuseKernel-test-${{ steps.get_date.outputs.date }}-universal7904.zip
        ./build.sh
